// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TODO.Entidades;

#nullable disable

namespace TODO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240625002213_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("TODO.Entidades.Asigna", b =>
                {
                    b.Property<int>("TareaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TareaId", "OperarioId");

                    b.HasIndex("OperarioId");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("TODO.Entidades.Operario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operarios");
                });

            modelBuilder.Entity("TODO.Entidades.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("TODO.Entidades.Asigna", b =>
                {
                    b.HasOne("TODO.Entidades.Operario", "Operario")
                        .WithMany("Tareas")
                        .HasForeignKey("OperarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TODO.Entidades.Tarea", "Tarea")
                        .WithMany("Operarios")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operario");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("TODO.Entidades.Operario", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("TODO.Entidades.Tarea", b =>
                {
                    b.Navigation("Operarios");
                });
#pragma warning restore 612, 618
        }
    }
}
